import type { Metadata } from 'next';

import localFont from 'next/font/local';

import './globals.css';

import { ModalContextProvider } from '@contexts/ModalContext';
import StoreProvider from '@providers/StoreProvider';
import TanstackQueryProvider from '@providers/TanstackQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: [{
    path: './font/PretendardVariable.woff2',
  },
  {
    path: './font/PretendardVariable.ttf',
  }],
  display: 'fallback',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <TanstackQueryProvider>
          <StoreProvider>
            <ModalContextProvider>
              {children}
            </ModalContextProvider>
          </StoreProvider>
        </TanstackQueryProvider>
        <div id="portal-root" />
      </body>
    </html>
  );
}
