import type { Metadata } from 'next';

import localFont from 'next/font/local';

import './globals.css';

import { ModalContextProvider } from '@contexts/ModalContext';
import MswProviders from '@providers/MswProvider';
import StoreProvider from '@providers/StoreProvider';
import TanstackQueryProvider from '@providers/TanstackQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: [{
    path: './font/PretendardVariable.woff2',
  },
  {
    path: './font/PretendardVariable.ttf',
  }],
  display: 'fallback',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <MswProviders>
          <TanstackQueryProvider>
            <StoreProvider>
              <ModalContextProvider>
                {children}
              </ModalContextProvider>
            </StoreProvider>
          </TanstackQueryProvider>
        </MswProviders>
        <div id="modal-root" />
        <div id="drawer-root" />
      </body>
    </html>
  );
}
